<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Bulk Delete' => 'Bulk Verwijderen',
    'Bulk Update' => 'Bulk Bewerken',
    'Cannot delete {model_object_name}' => 'Kan {model_object_name} niet verwijderen',
    'Cannot delete {model_object_name}: reason unknown' => 'Kan {model_object_name} niet verwijderen: reden onbekend',
    'Cannot delete {model_object_name}: {error}' => 'Kan {model_object_name} niet verwijderen: {error}',
    'Cannot delete {model_object_name}: {result}' => 'Kan {model_object_name} niet verwijderen: {result}',
    'Close' => 'Sluiten',
    'Copy' => 'Kopiëren',
    'Copy {model_object_name}' => 'Kopieer {model_object_name}',
    'Create' => 'Toevoegen',
    'Create new {model_name}' => 'Voeg nieuw {model_name} toe',
    'Delete \'{object}\' error:' => 'Verwijderen van \'{object}\' foutmelding:',
    'Delete failed' => 'Verwijderen gefaald',
    'Edit' => 'Aanpassen',
    'Error(s) saving' => 'Foutmelding(en) bij opslaan',
    'No fields found to update.' => 'Geen velden gevonden om op te slaan.',
    'Record not found' => 'Record not found',
    'Record {id} not found' => 'Record {id} niet gevonden',
    'Return' => 'Terug',
    'Saved successfully' => 'Opslaan succesvol',
    'The record is linked with {foreign_key}. Unlink before delete.' => '',
    'Update' => 'Opslaan',
    'Update \'{object}\' error:' => 'Opslaan  \'{object}\' foutmeldingen:',
    'Update {model_object_name}' => 'Opslaan {model_object_name}',
    '{model_name} {model_object_name} copied from {id}' => '{model_name} {model_object_name} gekopieerd van {id}',
    '{model_name} {model_object_name} created' => '{model_name} {model_object_name} aangemaakt',
    '{model_name} {model_object_name} updated' => '{model_name} {model_object_name} aangepast',
    '{model_object_name} deleted' => '{model_object_name} is verwijderd',
    '{object} Overview' => '{object} Overzicht',
    '{record_count,plural,=0{No} =1{One} other{#}} {mobel_name} deleted' => '{record_count,plural,=0{No} =1{One} other{#}} {mobel_name} verwijderd',
    '{record_count,plural,=0{no records} =1{one record} other{# records}} updated' => '{record_count,plural,=0{no records} =1{one record} other{# records}} aangepast',
];
